- name: npminstall
  workspaces:
    - name: source
      workspace: pipeline-workspace
  taskRef:
    name: npm
  runAfter:
    - clone
    - name: tests
  workspaces:
    - name: source
      workspace: pipeline-workspace
  taskRef:
    name: jasmine
  runAfter:
    - npminstall
    - name: build
  workspaces:
    - name: source
      workspace: pipeline-workspace
  taskRef:
    name: buildah
    kind: ClusterTask
  params:
  - name: IMAGE
    value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"
  runAfter:
    - tests
